import "@/styles/global.scss";
import "@/styles/reset.scss";
import "@/styles/utils/_mixins.scss"
import "@/styles/utils/_fonts.scss"
import { AnimatePresence } from "framer-motion";
import Head from "next/head";

export default function App({ Component, pageProps, router }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AnimatePresence mode="wait">
        <Component key={router} {...pageProps} />
      </AnimatePresence>
    </>
  );
}
